# Generated by Django 4.2.1 on 2023-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptAR_pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarEnAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('contacto', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('mensaje', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('contacto', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('mensaje', models.CharField(default='Valor predeterminado', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('contacto', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('mensaje', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Adoptante',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.AddField(
            model_name='transito',
            name='mensaje',
            field=models.CharField(default='Valor predeterminado', max_length=120),
        ),
    ]
