# Generated by Django 4.2.1 on 2023-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptAR_pagina', '0002_darenadopcion_donante_persona_delete_adoptante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darenadopcion',
            name='mensaje',
            field=models.CharField(default='Valor predeterminado', max_length=120),
        ),
    ]
